version: "3"
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    container_name: mongoose-getting-started
    hostname: localhost
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
